/*
 * io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition.h
 *
 * CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format &lt;.spec.name&gt;.&lt;.spec.group&gt;.
 */

#ifndef _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_H_
#define _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t;

#include "io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_spec.h"
#include "io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_status.h"
#include "io_k8s_apimachinery_pkg_apis_meta_v1_object_meta.h"



typedef struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t {
    char *api_version; // string
    char *kind; // string
    struct io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_t *metadata; //model
    struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_spec_t *spec; //model
    struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_status_t *status; //model

} io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t;

io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_create(
    char *api_version,
    char *kind,
    io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_t *metadata,
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_spec_t *spec,
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_status_t *status
);

void io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_free(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition);

io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_parseFromJSON(cJSON *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definitionJSON);

cJSON *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition);

#endif /* _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_H_ */

