#ifndef io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_TEST
#define io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition.h"
io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_t* instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(int include_optional);



io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_t* instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(int include_optional) {
  io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition = NULL;
  if (include_optional) {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_create(
      "0",
      "0",
      "0",
      "0",
      56,
      "0"
    );
  } else {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_create(
      "0",
      "0",
      "0",
      "0",
      56,
      "0"
    );
  }

  return io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition;
}


#ifdef io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_MAIN

void test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(int include_optional) {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_1 = instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(include_optional);

	cJSON* jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_1 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_1);
	printf("io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition :\n%s\n", cJSON_Print(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_1));
	io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_2 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_parseFromJSON(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_1);
	cJSON* jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_2 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_2);
	printf("repeating io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition:\n%s\n", cJSON_Print(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_2));
}

int main() {
  test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(1);
  test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition(0);

  printf("Hello world \n");
  return 0;
}

#endif // io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_MAIN
#endif // io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition_TEST
