/*
 * io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version.h
 *
 * CustomResourceDefinitionVersion describes a version for CRD.
 */

#ifndef _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_H_
#define _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t;

#include "io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_column_definition.h"
#include "io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_subresources.h"
#include "io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation.h"



typedef struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t {
    list_t *additional_printer_columns; //nonprimitive container
    int deprecated; //boolean
    char *deprecation_warning; // string
    char *name; // string
    struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t *schema; //model
    int served; //boolean
    int storage; //boolean
    struct io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_subresources_t *subresources; //model

} io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t;

io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_create(
    list_t *additional_printer_columns,
    int deprecated,
    char *deprecation_warning,
    char *name,
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t *schema,
    int served,
    int storage,
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_subresources_t *subresources
);

void io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_free(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version);

io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_parseFromJSON(cJSON *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_versionJSON);

cJSON *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_t *io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version);

#endif /* _io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_definition_version_H_ */

