#ifndef io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_TEST
#define io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation.h"
io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t* instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(int include_optional);

#include "test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_json_schema_props.c"


io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t* instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(int include_optional) {
  io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation = NULL;
  if (include_optional) {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_create(
       // false, not to have infinite recursion
      instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_json_schema_props(0)
    );
  } else {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_create(
      NULL
    );
  }

  return io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation;
}


#ifdef io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_MAIN

void test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(int include_optional) {
    io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_1 = instantiate_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(include_optional);

	cJSON* jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_1 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_1);
	printf("io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation :\n%s\n", cJSON_Print(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_1));
	io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_t* io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_2 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_parseFromJSON(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_1);
	cJSON* jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_2 = io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_convertToJSON(io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_2);
	printf("repeating io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation:\n%s\n", cJSON_Print(jsonio_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_2));
}

int main() {
  test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(1);
  test_io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation(0);

  printf("Hello world \n");
  return 0;
}

#endif // io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_MAIN
#endif // io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_custom_resource_validation_TEST
